---
title: "Unit_1_knitr"
author: "Scott Frazier"
date: "8/22/2021"
output: html_document
---


```{r}
head(cars)
```

```{r}
#grabbing all column data for rows 3 through 6
cars[3:6,]

#specific values, row and column
cars[4,2]

#same result as above, different method using column name
cars[4, "dist"]

#all data for row 3, and columns speed and dist
cars[3, c("speed", "dist")]

#objets are the nouns of R language, functions and commands are the verbs. They do things to objects.

#creating vector for round function
rounding = c(22.33, 45.6, 12, 15.777, 13.45)
rounding

#rounding the mean of the vector above
round(mean(rounding), digits = 1)

#use rm command to remove objects from the workspace

# use save.image command to save entire workspace in a binary-not plaint-text-RData file. 

# use load command to load saved workspace into R

#to see the most recent commands, use history command
#history

#use global options with options keyword
options(digits=1)
```
#use code chunks to include code in markup presentation documents
```{r CarsDistHist, echo=TRUE}
hist(cars[,"dist"])
```
