```{r imports}
library(tidyverse)
library(ggplot2)
library(tidyr)
library(xml2)
library(XML)
library(RCurl)
library(dplyr)
library(httr)
library(jsonlite)
library(WDI)
library(reshape2)
install.packages("reshape2")

```

```{r tidyData}
#data must be tidy first, each var has it's own column, each obs has its own row, each value has it's own cell

#wide data
olddata_wide <- read.table(header=TRUE, text='
subject genderage Control Treatment1 Treatment2
                           1   32_M     7.9  12.3  10.7
                           2   45_F     6.3  10.6  11.1
                           3   27_F     9.5  13.1  13.8
                           4   23_M    11.5  13.4  12.9
                           ')
olddata_wide$subject <- factor(olddata_wide$subject)
olddata_wide

#long version of data above, using gather and separate
data_long <- gather(olddata_wide, condition, measurement, Control:Treatment2, factor_key=TRUE)
data_long = data_long %>% separate(genderage, into = c("age","gender"))
data_long
str(data_long)
data_long$age = as.numeric(data_long$age)
str(data_long)

#use spread to go back to wide
data_wide <- spread(data_long, condition, measurement)
data_wide

#MERGING data sets
demographic <- read.table(header=TRUE, text='
                           subject age gender  condition 
                                  1     32   M    Control   
                                  2     45   F    Control     
                                  3     27   F    Control    
                                  4     23   M    Control       
                                  1     32   M Treatment1     
                                  2     45   F Treatment1       
                                  3     27   F Treatment1       
                                  4     23   M Treatment1       
                                  1     32   M Treatment2      
                                  2     45   F Treatment2      
                                  3     27   F Treatment2      
                                  4     23   M Treatment2
                           ')
demographic$subject <- factor(demographic$subject)
demographic
experimentData <- read.table(header=TRUE, text='
                         subject   condition measurement
                             1         Control         7.9
                             2         Control         6.3
                             3         Control         9.5
                             4         Control        11.5
                             1      Treatment1        12.3
                             2      Treatment1        10.6
                             3      Treatment1        13.1
                             4      Treatment1        13.4
                             1      Treatment2        10.7
                             2      Treatment2        11.1
                             3      Treatment2        13.8
                             4      Treatment2        12.9
                           ')
experimentData$subject <- factor(experimentData$subject)
experimentData
fullData = merge(demographic,experimentData,c("subject","condition"))
fullData

#using complete to add quarter 1 for year 2020
df = data.frame(year = c(2018,2018,2018,2018, 2019,2019,2019, 2019,2020,2020,2020), 
quarter = c(1,2,3,4,1,2,3,4,2,3,4), 
price = c(4.55,NA, 6.75, 8.2, 8.5, 9.6, 10.1, 11.0, 12.1, 13.1, 15.9),
char = c("Sunny","Roger",NA,"NA","Sunny","Roger",NA,"NA","Sunny","Roger",NA))
df %>% complete(year, quarter) #all possible combinations of year and quarter for the levels observed.
df %>% spread(year,price) #change to wide




```

```{r XML scraping}
data <-getURL("https://d396qusza40orc.cloudfront.net/getdata%2Fdata%2Frestaurants.xml")

doc <- xmlParse(data)
doc

names <- xpathSApply(doc,"//name",xmlValue)

zipcode = xpathSApply(doc,"//zipcode",xmlValue)

city_council_district <- xpathSApply(doc,"//councildistrict",xmlValue)

df = data.frame(names,zipcode,city_council_district)

df

df$sushi = ifelse(grepl("sushi", df$names, ignore.case = T), "is",
  ifelse(grepl("payroll", df$names, ignore.case = T), "is_not", "Other"))
df

df %>% filter(df$sushi == "is")

df$city_council_district <- factor(df$city_council_district, levels=c("1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14"))

df %>% ggplot(aes(x=city_council_district, fill = city_council_district)) + geom_bar() + ggtitle("Count of Restaurants by City Council District") + labs(y="Count of Restaurants", x="City Council District")

```

``` {r JSON and APIs}
#Data can be stored as null, numbers, strings, or Boolean, Data containers are square or curly brackets
results = as.data.frame(WDIsearch("gdp"))

RGI = results %>% filter(str_count(indicator, "\\.")==3)
RGI = as.data.frame(RGI) %>% separate(indicator, c("Topic", "General", "Specific", "Extension"))

RGI

test = data.frame(
insight1 = WDI(indicator = "BM.GSR.ROYL.CD", country=c("US"), start=1970, end=2000),
insight2 = WDI(indicator = "BM.GSR.ROYL.CD", country=c("ES"), start=1970, end=2000),
insight3 = WDI(indicator = "BM.GSR.ROYL.CD", country=c("GBR"), start=1970, end=2000))

test

head(insight1)
head(insight2)
head(insight3)

p = test %>% ggplot(aes()) + 
  geom_line(aes(x = insight1.year, y = insight1.BM.GSR.ROYL.CD, color = "insight1")) + 
  geom_line(aes(x = insight2.year, y = insight2.BM.GSR.ROYL.CD, color = "insight2")) + 
  geom_line(aes(x = insight3.year, y = insight3.BM.GSR.ROYL.CD, color = "insight3")) + ggtitle("Charges for use of intellectual property over time") + labs(x="Year", y="Charge Amount - USD", color = "Country")  + scale_color_manual(labels = c("United States", "Spain", "Great Britain"), values=c("red","blue","green"))

require(scales)
p + scale_y_continuous(labels=comma)

```



