```{r}
install.packages("ggthemes")
library(ggthemes)
library(tidyverse)
```

mpg = read.csv(file.choose(), header=T)

```{r}
#excel theme
mpg %>% ggplot(mapping = aes(x = hwy, y = cty)) + 
geom_point(position = "jitter") + 
ggtitle("City MPG v. Highway MPG") + 
theme_excel()

#theme economist
mpg %>% ggplot(mapping = aes(x = hwy, y = cty)) + 
geom_point(position = "jitter") + 
ggtitle("City MPG v. Highway MPG") + 
theme_economist()

#theme 538
mpg %>% ggplot(mapping = aes(x = hwy, y = cty)) + 
geom_point(position = "jitter") + 
ggtitle("City MPG v. Highway MPG") + 
theme_fivethirtyeight()

#trying random themes
mpg %>% ggplot(mapping = aes(x = hwy, y = cty)) + 
geom_point(position = "jitter") + 
ggtitle("City MPG v. Highway MPG") + 
theme_solarized()

mpg %>% ggplot(mapping = aes(x = hwy, y = cty)) + 
geom_point(position = "jitter") + 
ggtitle("City MPG v. Highway MPG") + 
theme_wsj()

mpg %>% ggplot(mapping = aes(x = hwy, y = cty)) + 
geom_point(position = "jitter") + 
ggtitle("City MPG v. Highway MPG") + 
theme_stata()
```
