```{r imports}
library(ggplot2)
library(tidyverse)
library(plotly)

```

basketball = read.csv(file.choose(), header=T)

```{r visualizations}

head(basketball)

#question 1
plot1 = basketball %>% ggplot(mapping = aes(x=position, fill = basketball$position)) + geom_bar() + ggtitle("Count of positions")
plot1

#question 2
basketball[basketball$position == "C",] %>% ggplot(aes(x=weight)) + geom_bar(color="white")+ ggtitle("Count of positions (by weight) - Center")

basketball[basketball$position == "F",] %>% ggplot(aes(x=weight)) + geom_bar(color="blue") + ggtitle("Count of positions (by weight) - Forward")

#question 3,
basketball[basketball$position == "C",] %>% ggplot(aes(x=height)) + geom_bar(color="black")+ ggtitle("Count of positions (by height) - Center")

basketball[basketball$position == "F",] %>% ggplot(aes(x=height)) + geom_bar(color="black") + ggtitle("Count of positions (by height) - Forward")

#question 4
basketball %>% ggplot(aes(x=position, y=height)) + geom_boxplot()
sapply(basketball, class)

#question 5
basketball %>% ggplot(aes(x=weight, y=height, color=position)) + geom_point() + ggtitle("Player Height vs. Weight")

#question 6
ggplot(data = basketball) +
geom_point(mapping = aes(x=weight, y=height, color=position)) +
facet_wrap(~position)

#question 7
basketball %>% ggplot(mapping = aes(x=year_start, y=height)) + geom_point()

#question 8
plot_3d = plot_ly(basketball, x = ~year_start, y = ~weight, z = ~height, color= ~position) %>%
   add_markers() %>%
   layout(scene = list(xaxis = list(title = 'Height'),
                      yaxis = list(title = 'Weight'),
                      zaxis = list(title = 'Year Start')))
plot_3d

#question 9
basketball %>% ggplot(aes(x=year_start)) + geom_bar(aes(fill=position)) + ggtitle("Count of players vs. Year Started.") + labs(subtitle="Filtered by position")

```

```{r visuals2}
edu = read.csv(file.choose(), header=T)
head(edu)


edu_level = edu["Educ"]
df76 = data.frame(edu_level)
df76

income = edu["Income2005"]
df <- data.frame(edu_level, income)
df
```

```{r vizzfinal}
#trying to aggregate to get the means of income in relation to edu level
aggregate(.~income, data=df, mean)

new_vector = df$edu_level
new_vector

new_vec_2 = df[['edu_level']]
new_vec_2

sapply(split(df$edu_level, df$income), mean) 

df %>% group_by(edu_level) %>% summarize(mean(income))


edu %>% ggplot(aes(x=Educ, y=Income2005)) + geom_point()
edu %>% ggplot(aes(x=Educ, fill=Income2005)) + geom_bar(position="dodge")

p = ggplot(data=edu, aes(x=Educ, y=Income2005, group=1, color=Income2005))+
  geom_point() + geom_jitter() + ggtitle("Income vs Education Level") + xlab("Education Level") + ylab("Income")
p

require(scales)
p + scale_y_continuous(labels = comma)


head(sort(edu$Income2005, decreasing=TRUE), 5)
max(edu$Income2005)

```

