names = [
'Assists (raw)',
'Assists - Most in Game (raw)',
'Critical Hit Damage (raw)',
'Critical Hit Damage - Most in Game (raw)',
'Critical Hit Kills (raw)',
'Critical Hit Kills - Most in Game (raw)',
'Critical Hits (raw)',
'Critical Hits - Most in Game (raw)',
'Critical Hits - Most in Life (raw)',
'Damage Done (raw)',
'Damage Done - Most in Game (raw)',
'Damage Done - Most in Life (raw)',
'Deaths (raw)',
'Defensive Assists (raw)',
'Defensive Assists - Most in Game (raw)',
'Eliminations (raw)',
'Eliminations - Most in Game (raw)',
'Eliminations - Most in Life (raw)',
'Final Blows (raw)',
'Final Blows - Most in Game (raw)',
'Games Played (raw)',
'Games Tied (raw)',
'Games Won (raw)',
'Healing Accuracy - Best in Game (raw)',
'Healing Done (raw)',
'Healing Done - Most in Game (raw)',
'Hero Damage Done (raw)',
'Hero Damage Done - Most in Game (raw)',
'Hero Damage Done - Most in Life (raw)',
'Hero Wins (raw)',
'Kill Streak - Best (raw)',
'Melee Kills (raw)',
'Obj Contest Time (raw)',
'Obj Contest Time - Most in Game (raw)',
'Objective Kills (raw)',
'Objective Kills - Most in Game (raw)',
'Objective Time (raw)',
'Objective Time - Most in Game (raw)',
'Offensive Assists (raw)',
'Offensive Assists - Most in Game (raw)',
'Scoped Accuracy - Best in Game (raw)',
'Scoped Critical Hit Kills (raw)',
'Scoped Critical Hits (raw)',
'Scoped Critical Hits - Most in Game (raw)',
'Self Healing (raw)',
'Self Healing - Most in Game (raw)',
'Solo Kills (raw)',
'Solo Kills - Most in Game (raw)',
'Time Played (raw)',
'Time Spent on Fire (raw)',
'Time Spent on Fire - Most in Game (raw)',
'Ultimate Damage (raw)',
'Weapon Accuracy - Best in Game (raw)'
]

for column in names:
    print(f"{column.split("(raw)")[0]} = SUM('hero_clean - main_stats'[{column}])")