```{r imports}
library(ggplot2)
library(tidyverse)
library(GGally)
#library(nycflights13)
```
mpg
fifa = read.csv(file.choose(), header=T)
```{r select}
# select is for columns only
mpg %>% select(class, hwy, cty)

#using select and GGally
mpg %>% select(class, cty, hwy) %>% ggpairs(aes(color=class))

#fifa dataset
fifa %>% select(Finishing, BallControl, ShotPower) %>% ggpairs()

fifa %>% filter(Preferred.Foot=="Right" | Preferred.Foot=="Left") %>% 
  select(Finishing, BallControl, ShotPower, Preferred.Foot) %>% 
  ggpairs(aes(color=Preferred.Foot))

unique(fifa)

```

```{r mutate}
#use mutate to create new variables
mpgDiff = mpg %>% mutate(diffHC = hwy-cty)
mpgDiff

#making a graph using ggplot2 and mutate
mpg %>% mutate(diffHC= hwy - cty) %>% ggplot(aes(x=displ, y=diffHC)) + geom_point()

#coloring the scatter plot
mpg %>% mutate(diffHC= hwy - cty) %>% ggplot(aes(x=displ, y=diffHC, color=class)) + geom_point()

```

``` {r group_by}
#summary chart of the mean city mpg, for each class
mpg %>% group_by(class) %>% summarize(meanCTY = mean(cty), count = n())

#group by with 2 variables, class first, and then year within class
mpg %>% group_by(class, year) %>% summarize(meanCTY = mean(cty), count = n())

#stat-identity 
mpg %>% group_by(class) %>% summarize(sum(cty))

#fifa, mean function has na.rm, which removes NAs then takes the mean.
fifa %>% filter(!is.na(BallControl)) %>% group_by(Position) %>% summarize(meanBC = mean(BallControl), count = n()) %>% ggplot(aes(x=Position, y=meanBC)) + geom_col()

#using arrange for quick EDA
fifa %>% filter(!is.na(BallControl)) %>% group_by(Position) %>% summarize(meanBC = mean(BallControl), count = n()) %>% arrange(meanBC) %>% print(n=28)

```
