```{r imports}
library(GGally)
library(tidyverse)
library(ggplot2)
```
mpg
fifa = read.csv(file.choose(), header = T)
```{r factors}
mpg %>% ggplot(aes(x=hwy, y=cty, color = as.factor(cyl))) + geom_point()

#storing values in object, list levels
cylinderFact = factor(mpg$cyl)
cylinderFact

#change data typer to factor, not numeric for cylinders
levels(cylinderFact) = c("Four", "Five", "Six", "Eight")
cylinderFact

#plotting the above
mpg %>% mutate(cyl_factor = cylinderFact) %>% ggplot(aes(x = hwy, y = cty, color = cyl_factor)) + geom_point()

#use arrange to order fifa data
fifa_BC = fifa %>% filter(!is.na(BallControl)) %>% group_by(Position) %>% summarize(meanBC = mean(BallControl), count = n()) %>% arrange(meanBC) %>% print(n=28)

#reorder our levels
fifa_BC$Position = factor(fifa_BC$Position, level = fifa_BC$Position[order(fifa_BC$meanBC)])
fifa_BC$Position

#ordered results
fifa_BC %>% ggplot(aes(x=Position, y=meanBC)) + geom_col()

```

```{r cut}
#want to turn continous var into factor?
displ_Fac = cut(mpg$displ, breaks = c(1,4,6,8), labels = c("Low", "Medium", "High"))

mpg %>% mutate(displ_Fac = displ_Fac) %>% ggplot(aes(x=hwy, y=cty, color = displ_Fac) + geom_point()


```